from collections.abc import Callable, Iterable
from typing import Any

__version__: str

class WizlaunchError(RuntimeError):
    code: str
    operation: str
    technical_message: str | None
    details: dict[str, Any]

class RuntimeNotConfiguredError(WizlaunchError): ...
class AccountStorageUnavailableError(WizlaunchError): ...

def configure_runtime(
    agent_manager: Any,
    *,
    generation_context: Any,
    login_router: Callable[[str, dict[str, Any]], None] | None = None,
) -> None: ...
def clear_runtime() -> None: ...
def capture_runtime(expected_instance_id: object | None = None) -> Any: ...
def prompt_save_account(nickname: str) -> None: ...
def delete_account(nickname: str) -> None: ...
def list_accounts(*, _runtime_binding: Any = ...) -> list[str]: ...
def reorder_accounts(ordered: Iterable[str], *, _runtime_binding: Any = ...) -> None: ...
def has_account(nickname: str, *, _runtime_binding: Any = ...) -> bool: ...
def validate_account(nickname: str) -> str | None: ...
def get_account_steam(nickname: str, *, _runtime_binding: Any = ...) -> bool | None: ...
def set_account_steam(nickname: str, steam: bool) -> None: ...
def get_window_config(
    nickname: str,
) -> tuple[int, int, int, int, int, int, bool, bool] | None: ...
def set_window_config(
    nickname: str,
    x: int,
    y: int,
    width: int,
    height: int,
    resolution_width: int,
    resolution_height: int,
    locked: bool,
    borderless: bool = False,
) -> None: ...
def clear_window_config(nickname: str) -> None: ...
def update_player_gid(nickname: str, gid: int, *, _runtime_binding: Any = ...) -> None: ...
def get_player_gid(nickname: str, *, _runtime_binding: Any = ...) -> int | None: ...
def get_nickname_by_gid(gid: int, *, _runtime_binding: Any = ...) -> str | None: ...
def launch_instance(
    nickname: str,
    game_path: str,
    login_server: str | None = None,
    timeout_secs: int = 30,
) -> int | str: ...
def launch_instances(
    nicknames: Iterable[str],
    game_path: str,
    login_server: str | None = None,
    timeout_secs: int = 30,
) -> dict[str, int | str]: ...
def kill_instance(handle: int | str) -> bool: ...
def get_wizard_handles() -> list[int | str]: ...
