[package]
name = "deimos-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
deimos-core.workspace = true
memchr.workspace = true
serde.workspace = true
serde_json.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }
